# Generated by Django 2.2.24 on 2021-10-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.TextField(default='', max_length=280),
            preserve_default=False,
        ),
    ]
